server:
  port: 8205
spring:
  application:
    name: service-oss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      server-addr: localhost:8848
aliyun:
  oss:
    ak: ${aliyun-ak}
    sk: ${aliyun-sk}
    bucket: biluoer
    endpoint: oss-cn-beijing.aliyuncs.com
