server:
  port: 8201
spring:
  application:
    name: service-hosp

  # mysql连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: ${common-pwd}

  # jackson全局日期格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/yygh_hosp
      password: ${common-pwd}

  # nacos
  cloud:
    nacos:
      server-addr: localhost:8848

  redis:
    host: ${redis-host}
    port: 6379
    password: ${common-pwd}

  # rabbit-mq
  rabbitmq:
    host: ${redis-host}
    port: 5672
    username: rabbitmq
    password: ${common-pwd}

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
